# Generated by Django 2.0.7 on 2018-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
