# Generated by Django 2.0.7 on 2018-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180912_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
