# Generated by Django 2.0.7 on 2018-10-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_claimdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimdata',
            old_name='ItemId',
            new_name='ItemID',
        ),
    ]
